import { LaborType } from "../_models/labor-type";
import { HWStatus } from "../_models/hw-status";
import { Shift } from "../_models/shift";
import { JobClassification } from "../_models/job-classification";
import { CDFLocation } from "../_models/cdflocation";
import { StaffCBMBenefit } from "../_models/staff-cbm-benefit";
import { StaffAESBenefit } from "../_models/staff-aes-benefit";
import { StaffNonUnionBenefit } from "../_models/staff-non-union-benefit";

export class WctReportStaff{
   Classification?: string;
   BaseWage: number;
   TaxesAndIns : number;
   EffectiveTaxesAndInsurance: number;
   HealthAndWelfare: number;
   Pension401K: number;
   TrainingFund: number;
   Other: number;
   UniformCharges: number;
   TrustFundAuditCompliance: number;
   TechnologyHosting_Retention: number;
   CyberSecurity:number;
   SubTotalHourlyRate: number;
    Safety: number;
    Overhead: number;
    Profit: number;
    SFGRT: number;
    SalesTax: number;
    BAndOTax: number;
    TotalHourlyRate: number;
    TotalMonthly: number;
    BaseWageOT: number;
    TaxesAndInsOT: number;
    HealthAndWelfareOT: number;
    Pension401KOT: number;
    TrainingFundOT: number;
    OtherOT: number;
    UniformChargesOT: number;
    TrustFundAuditComplianceOT: number;
    TechnologyHosting_RetentionOT: number;
    CyberSecurityOT: number;
    OverTimeSubTotal: number;
    SafetyOT: number;
    OverheadOT: number;
    ProfitOT: number;
    SFGRTOT: number;
    SalesTaxOT: number;
    BAndOTaxOT: number;
    OverTimeTotal: number;
    BaseWageDT: number;
    TaxesAndInsDT: number;
    HealthAndWelfareDT: number;
    Pension401KDT: number;
    TrainingFundDT: number;
    OtherDT: number;
    UniformChargesDT: number;
    TrustFundAuditComplianceDT: number;
    TechnologyHosting_RetentionDT: number;
    CyberSecurityDT: number;
    DoubleTimeSubTotal: number;
    SafetyDT: number;
    OverheadDT: number;
    ProfitDT: number;
    SFGRTDT: number;
    SalesTaxDT: number;
    BAndOTaxDT: number;
    DoubleTimeTotal: number;
    BaseWageDTH: number;
    TaxesAndInsDTH: number;
    HealthAndWelfareDTH: number;
    Pension401KDTH: number;
    TrainingFundDTH: number;
    OtherDTH: number;
    UniformChargesDTH: number;
    TrustFundAuditComplianceDTH: number;
    TechnologyHosting_RetentionDTH: number;
    CyberSecurityDTH: number;
    DoubleTimeAndHalfSubTotal: number;
    SafetyDTH: number;
    OverheadDTH: number;
    ProfitDTH: number;
    SFGRTDTH: number;
    SalesTaxDTH: number;
    BAndOTaxDTH: number;  
    DoubleTimeAndHalfTotal: number;
}